### PR TITLE
fix(Wikilinks): Removing slug in wiki seems to repear my links problem

### PR DESCRIPTION
**Pull request by Mara-Li**
Removing slug in links for Wikilinks (it the only I try) seems to repear my problem (see #41 and #40)

### CODE REVIEW

**Comment by ooker777** [comment]
this repo seems unsupported right now. Do you consider to fork it and use that fork in Obsidian Publisher for better result?

**Comment by Mara-Li** [comment]
It's already the case @ooker777

**Comment by ooker777** [comment]
How do you implement it? Looking at the [`mkdocs.yml`](https://github.com/ObsidianPublisher/template-netlify-vercel/blob/05a83f58086ad1b6abab4f0a31126dabf267f989/mkdocs.yml#L89) it seems that it still use this plugin. Is that correct?

Btw, I think this is also a bug of it: [Expecting `\[\[./a/index\]\]` to returns `<a href="a/"`, get `<a href="a/index"` · Issue #53 · orbikm/mkdocs-ezlinks-plugin](https://github.com/orbikm/mkdocs-ezlinks-plugin/issues/53 "Expecting `[[./a/index]]` to returns `&lt;a href=&quot;a/&quot;`, get `&lt;a href=&quot;a/index&quot;` · Issue #53 · orbikm/mkdocs-ezlinks-plugin")

**Comment by Mara-Li** [comment]
As the fork use the same class, it uses the same settings. But, in requirements, it dl my fork.

**Comment by ooker777** [comment]
I didn't realize that you rename it from `mkdocs-ezlinks-plugin` to [`mkdocs-ezlinked-plugin`](https://pypi.org/project/mkdocs-ezlinked-plugin/ "mkdocs-ezlinked-plugin · PyPI")

**Comment by Mara-Li** [comment]
Hello, 
As i rebranded the plugin and removed the tags, I will close this PR.
Feel free to follow the mkdocs-obsidian-links for more!

**Pull request closed without merging**
